#name: lessdeep
channels:
  - defaults
  - pytorch
dependencies:
  - jupyter
  - matplotlib
  - ipywidgets
  - numpy
  - scipy
  - pandas
  - pytorch
  - python-lmdb
  - pip:
    - tqdm
    - keras-tqdm
    - torchvision
