#name: yama
channels:
  - defaults
  - pytorch
dependencies:
  - bcolz
  - jupyter
  - notebook
  - matplotlib
  - numpy
  - scipy
  - pillow
  - pandas
  - pytorch
  - python >= 3.5.0
#  - futures  # for python 2.7
  - pip:
    - ipywidgets
    - keras-tqdm
    - tqdm
    - torchvision
    - urllib3
